== Other Related Activities

This section provides an overview of related activities identified by the authors of this white paper.

=== W3C Linked Building Data Community Group

==== Scope of Activity

This group brings together experts in the area of building information modelling (BIM) and Web of Data technologies to define existing and future use cases and requirements for linked data based applications across the life cycle of buildings. A list of recommended use cases will be produced by this community group. The envisioned target beneficiaries of this group are both industrial and governmental organisations who use data from building information modelling applications and other data related to the building life cycle (sensor data, GIS data, material data, geographical data, and so forth) to achieve their business processes and whom will benefit from greater integration of data and interoperability between their data sets and the wider linked data communities. [15]

==== Web Site(s)

- https://www.w3.org/community/lbd/

==== Source Repositories

- https://github.com/w3c-lbd-cg/lbd

==== Liaisons

- TBD

=== ISO/IEC JTC 1/SC 32/WG 3

==== Scope of Activity

SC 32 provides enabling technologies to promote harmonization of data management facilities across sector-specific areas. Specifically, SC 32 standards include:

reference models and frameworks for the coordination of existing and emerging standards;
definition of data domains, data types, and data structures, and their associated semantics;
languages, services, and protocols for persistent storage, concurrent access, concurrent update, and interchange of data;
methods, languages, services, and protocols to structure, organize, and register metadata and other information resources associated with sharing and interoperability, including electronic commerce. [16]

==== Web Site(s)

- TBD

==== Source Repositories

- TBD

==== Liaisons

- TBD


