== Introduction
//write text in as many clauses as necessary. Use one document or many, your choice!

The spatial aspect of data is a core characteristic. Spatial information provides the capability to provide both location and shape as a context to whatever it relates to. The authors of this White Paper believe that semantic and graph technologies, together with  strategies for Linked Data, will increase the value that can be extracted from (geo)spatial data.

Although many current and past work within the OGC involves semantic and graph technologies, there is one main applicable OGC standard: GeoSPARQL. GeoSPARQL offers both semantics for representing geospatial data and it specifies how geospatial data that are expressed using the Resource Description Framework (RDF) can be queried using SPARQL, the query language for RDF. 

This paper does four things. Firstly, it describes the benefits of representing geospatial data using semantics, graph, and web technologies. Secondly, it gives an overview of the current capabilties of the GeoSPARQL standard, showing that many benefits of semantic and graph technologies are already within reach. Thirdly, it outlines some shortcomings of the existing GeoSPARQL implementation specification that, if addressed, would unlock its potential to a greater extent, and could significantly increase its user base. Finally, it identifies other related activities that are current at the time of editing this paper. In doing so, it establishes liaison's between the different activities in an attempt to achieve alignment.

The purpose of this paper is to provoke further thought about a best course for further development of the GeoSPARQL standard, and to invite active involvement in that development. Particularly, the involvement of people and organisations that until now have not been able to put GeoSPARQL to good use, either because of perceived limitations or because of unfamiliarity with the standard, will be highly valued. Also, since one development under consideration is to make provisions for use of GeoSPARQL with non-geographic spatial data, those that see opportunities for using spatial data in a broad sense together with the aforementioned technologies are cordially invited to share their views.  

== Semantic Technologies

Semantic technologies, in the scope of this document, relate to the use of formal ontologies to describe concepts: the relationships between "things" and categories of "things". There are a number of goals for using these technologies, which often relate to providing the capability to reason over the data and simplified dealing with heterogeneous data sources. Example goals include enabling machine readability, and federated searching. A major area in which semantic technologies are used is the Semantic Web, the part of the World Wide Web dealing with semantics.

A concept closely related to the Semantic Web is Linked Data. Linked Data is the name given to the idea of using the common Web communication protocol HTTP(S) to link raw data from different sources, much in the same way as HTML documents can cross-reference each other using hyperlinks. Data sets as well as individual data elements are identified by HTTP(S) IRIs, which act both as unique and persistent identifiers and allow direct retrieval of raw data. This leads to a web of data that can be tapped into by both human users and software. The concept is applicable to open data as well as data that are not supposed to be accessed by everyone.

== Graph Technologies

Graph technologies, in the scope of this document, relate to storage and querying of data items stored as nodes and edges. Each node represents an entity or an instance (e.g., a person, place, or thing). Each edge represents a relationship between nodes. Graph databases are optimised for querying graph data structures making them useful for goals like computing the shortest path between two nodes or finding nodes related by particular patterns of relationship. This contrasts with the strict schema of the model used by relational databases that imposes limitations on how relationships can be queried. Graph systems also define their schema "as they go" since all nodes and edges are defined and new ones can always be added with their definitions. This makes data model expansion easy but still manageable which contrasts with both more fixed relational models and un-governed noSQL systems.
