== Current capabilities

=== GeoSPARQL

GeoSPARQL is the most common geospatial extension of SPARQL. It was accepted as an OGC standard in 2012.

According to the standard document, "The OGC GeoSPARQL standard supports representing and querying geospatial data on the Semantic Web. GeoSPARQL defines a vocabulary for representing geospatial data in RDF, and it defines an extension to the SPARQL query language for processing geospatial data".

==== Requirements addressed

GeoSPARQL addresses the following requirements.

===== Requirement 1: Integrate with SPARQL

Implementations shall support the SPARQL Query Language for RDF [W3C SPARQL], the SPARQL Protocol for RDF [W3C SPARQL Protocol] and the SPARQL Query Results XML Format [W3C SPARQL Result Format].

===== Requirement 2: Represent Spatial Objects in SPARQL

Implementations shall allow the RDFS class geo:SpatialObject to be used in SPARQL graph patterns.

===== Requirement 3: Represent Features in SPARQL

Implementations shall allow the RDFS class geo:Feature to be used in SPARQL graph patterns.

===== Requirement 4: Represent Simple Features Spatial Relationships in SPARQL

Implementations shall allow the properties geo:sfEquals, geo:sfDisjoint, geo:sfIntersects, geo:sfTouches, geo:sfCrosses, geo:sfWithin, geo:sfContains, geo:sfOverlaps to be used in SPARQL graph patterns

===== Requirement 5: Represent Egenhofer Spatial Relationships in SPARQL

Implementations shall allow the properties geo:ehEquals, geo:ehDisjoint, geo:ehMeet, geo:ehOverlap, geo:ehCovers, geo:ehCoveredBy, geo:ehInside, geo:ehContains to be used in SPARQL graph patterns

===== Requirement 6: Represent RCC8 Spatial Relationships in SPARQL

Implementations shall allow the properties geo:rcc8eq, geo:rcc8dc, geo:rcc8ec, geo:rcc8po, geo:rcc8tppi, geo:rcc8tpp, geo:rcc8ntpp, geo:rcc8ntppi to be used in SPARQL graph patterns

===== Requirement 7: Represent Geometry in SPARQL

Implementations shall allow the RDFS class geo:Geometry to be used in SPARQL graph patterns

===== Requirement 8: Integration of Geometry with aspatial data

Implementations shall allow the properties geo:hasGeometry and geo:hasDefaultGeometry to be used in SPARQL graph patterns

===== Requirement 9:

Implementations shall allow the properties geo:dimension, geo:coordinateDimension, geo:spatialDimension, geo:isEmpty, geo:isSimple, geo:hasSerialization to be
used in SPARQL graph patterns

===== Requirement 10: Conformance Requirements for Geometry Encoding

All RDFS Literals of type geo:wktLiteral shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid geo:wktLiterals are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1]

===== Requirement 11: Adopt WGS84 as Default CRS (change to more explicit code)

The URI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> shall be assumed as the spatial reference system for geo:wktLiterals that do not specify an explicit spatial reference system URI.

===== Requirement 12: Inherit axis order from Spatial Reference System

Coordinate tuples within geo:wktLiterals shall be interpreted using the axis order defined in the spatial reference system used

===== Requirement 13: Interpret empty RDFS as empty Geometry

An empty RDFS Literal of type geo:wktLiteral shall be interpreted as an empty geometry

===== Requirement 14: Represent Geometries as WKT

Implementations shall allow the RDF property geo:asWKT to be used in SPARQL graph patterns

===== Requirement 15: Comform with GML

All geo:gmlLiterals shall consist of a valid element from the GML schema that implements a subtype of GM_Object as defined in [OGC 07-036]

===== Requirement 16: Interpret empty GML Literals as empty Geometry

An empty geo:gmlLiteral shall be interpreted as an empty geometry

===== Requirement 17: Document GML profiles

Implementations shall document supported GML profiles

===== Requirement 18: Represent Geometries as GML

Implementations shall allow the RDF property geo:asGML to be used in SPARQL graph patterns

===== Requirement 19:

Implementations shall support geof:distance, geof:buffer, geof:convexHull, geof:intersection, geof:union, geof:difference, geof:symDifference, geof:envelope and geof:boundary as SPARQL extension functions, consistent with the definitions of the corresponding functions (distance, buffer, convexHull, intersection, difference, symDifference, envelope and boundary respectively) in Simple Features [ISO 19125-1]

===== Requirement 20: Support Simple Features getSRID in SPARQL Queries

Implementations shall support geof:getSRID as a SPARQL extension function.

===== Requirement 21:

Implementations shall support geof:relate as a SPARQL extension function, consistent with the relate operator defined in Simple Features [ISO 19125-1]

===== Requirement 22: Support Simple Features Spatial Relationship Functions in SPARQL Queries

Implementations shall support geof:sfEquals, geof:sfDisjoint, geof:sfIntersects, geof:sfTouches, geof:sfCrosses, geof:sfWithin, geof:sfContains, geof:sfOverlaps as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features [ISO 19125-1]

===== Requirement 23: Support Egenhofer Spatial Relationship Functions in SPARQL Queries

Implementations shall support geof:ehEquals, geof:ehDisjoint, geof:ehMeet, geof:ehOverlap, geof:ehCovers, geof:ehCoveredBy, geof:ehInside, geof:ehContains as SPARQL extension functions, consistent with their corresponding DE- 9IM intersection patterns, as defined by Simple Features [ISO 19125-1]

===== Requirement 24: Support RCC8 Spatial Relationship Functions in SPARQL Queries

Implementations shall support geof:rcc8eq, geof:rcc8dc, geof:rcc8ec, geof:rcc8po, geof:rcc8tppi, geof:rcc8tpp, geof:rcc8ntpp, geof:rcc8ntppi as SPARQL extension functions, consistent with their corresponding DE-9IM intersection patterns, as defined by Simple Features [ISO 19125-1]

===== Requirement 25: Support RDFS Entailment

Basic graph pattern matching shall use the semantics defined by the RDFS Entailment Regime [W3C SPARQL Entailment]

===== Requirement 26:

Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the one in the specified version of Simple Features [ISO 19125-1]

===== Requirement 27:

Implementations shall support graph patterns involving terms from an RDFS/OWL class hierarchy of geometry types consistent with the GML schema that implements GM_Object using the specified version of GML [OGC 07-036]

===== Requirement 28: Support RIF Entailment for Simple Features Spatial Relationships

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime [W3C SPARQL Entailment] for the RIF rules [W3C RIF Core] geor:sfEquals, geor:sfDisjoint, geor:sfIntersects, geor:sfTouches, geor:sfCrosses, geor:sfWithin, geor:sfContains, geor:sfOverlaps

===== Requirement 29: Support RIF Entailment for Egenhofer Spatial Relationships

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime [W3C SPARQL Entailment] for the RIF rules [W3C RIF Core] geor:ehEquals, geor:ehDisjoint, geor:ehMeet, geor:ehOverlap, geor:ehCovers, geor:ehCoveredBy, geor:ehInside, geor:ehContains

===== Requirement 30: Support RIF Entailment for RCC8 Spatial Relationships

Basic graph pattern matching shall use the semantics defined by the RIF Core Entailment Regime [W3C SPARQL Entailment] for the RIF rules [W3C RIF Core] geor:rcc8eq, geor:rcc8dc, geor:rcc8ec, geor:rcc8po, geor:rcc8tppi, geor:rcc8tpp, geor:rcc8ntpp, geor:rcc8ntppi
