== Introduction
//write text in as many clauses as necessary. Use one document or many, your choice!

The spatial aspect of data is being recognised as a core data dimension. Spatial information provides the capability to answer the question "where", providing additional context to whatever it relates to. The authors of this White Paper believe that semantic and graph technologies will increase the value that can be extracted from (geo)spatial data. 

This paper has two purposes. Firstly, to describe the benefits of representing geospatial data using semantics and graph technologies. Secondly, to outline some shortcomings of the existing GeoSPARQL implementation specification that, if addressed, would unlock its potential to a greater extent.

== Semantic Technologies

Semantic technologies, in the scope of this document, relate to the use of formal ontologies to describe concepts: the relationships between "things" and categories of "things". There are a number of goals for using these technologies, which often relate to providing the capability to reason over the data and simplified dealing with heterogeneous data sources. Example goals include enabling machine readability, and federated searching.

== Graph Technologies

Graph technologies, in the scope of this document, relate to storage and querying of data items stored as nodes and edges. Each node represents an entity or an instance (e.g., a person, place, or thing). Each edge represents a relationship between nodes. Graph databases are optimised for querying graph data structures making them useful for goals like computing the shortest path between two nodes or finding nodes related by particular patterns of relationship. This contrasts with the strict schema of the model used by relationa databases that imposes limitations on how relationships can be queried. Graph systems also define their schem "as they go" since all nodes and edges are defined and new ones can always be added with their definitions. This makes data model expansion easy but still managable which contrasts with both more fixed relational models and un-goverend noSQL systems.