== Learnings from use

This section provides an overview of feedback received on the current version of the GeoSPARQL standard (version 1.0). This feedback helps to identify some of the barriers to use, and to outline requirements that have not been addressed that may encourage greater uptake.

=== Proposed extensions to GeoSPARQL 1.0

==== Extension 1: Extend expressive power of ontology for encountered use cases

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=601

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/15

===== Category

Semantic improvement

===== Description

We request extensions to the GeoSPARQL OWL ontology that includes details it doesn't cater for such as indicating spatial resolution, areas, proportional relations (e.g. area overlaps) and roles for multiple Geometry objects relating to a single Feature.

We have packaged the extensions we are already using in an ontology that is mostly built on GeoSPARQL but it also uses elements from QUDT and the some supporting datatype vocabularies.

The "GeoSPARQL Extensions Ontology" is online, and can be found here: https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/.

==== Extension 2: Make underlying definitions available on the semantic web

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=600

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/14

===== Category

Accessibility

===== Description

GeoSPARQL is currently lacking in semantics that are available on the semantic web. For example, the concept of Geometry is not explained in GeoSPARQL itself, but has in its text definition a pointer to ISO 19107: "This class is equivalent to the UML class GM_Object defined in ISO 19107". Should one look up that document on the web, a paywall from ISO is hit. Such fundamental definitions should be directly accessible to consumers, both human and machine, on the semantic web, either as part of GeoSPARQL or as another web vocabulary.

==== Extension 3: Include all functions already described in Simple Features for SQL

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=599

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/13

===== Category

Geospatial processing

===== Description

GeoSPARQL describes a number of SPARQL functions that can be implemented by developers of SPARQL endpoints. It would be beneficial for working with spatial data in SPARQL if more ways of interacting with spatial data were available. The routines and functions described in the Simple Features for SQL specification (06-104r4) are well known and have been implemented in different libraries and data storage systems. It could be a relatively simple effort to transpose the existing definitions to RDFS/OWL, so developers of SPARQL systems can implement those often very useful functions, either by using existing libraries, or by new development.

==== Extension 4: Add semantics for CRS

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=598

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/12

===== Category

Semantic improvement

===== Description

Descriptions of Coordinate Reference Systems (CRS) are important in correct interpretation of spatial data, and in working with that kind of data. However, CRS descriptions are not readily available as Linked Data. Therefore, it would be good to have GeoSPARQL use a standard ontology for describing CRS, either as an extension or module of GeoSPARQL itself, or an endorsed external ontology.

==== Extension 5: Explicitly expect significant digits in numerical data

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=597

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/11

===== Category

Semantic improvement

===== Description

Numerical data published using GeoSPARQL often have an unrealistic amount of digits. At the same time, there is no standardized way to express spatial resolution yet. Both these problems can be addressed when numerical data, published using GeoSPARQL, are explicitly expected to have only significant digits.

==== Extension 6: Widen the scope to all spatial data

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=594

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/9

===== Category

Increased scope

===== Description

GeoSPARQL's scope is geographic data, as the name says. Less explicit, GeoSPARQL is only about vector data. However, there is a need for a web ontology that can be used to work with all kinds of spatial data. GeoSPARQL seems to be the best candidate for realization of a domain independent ontology for spatial data.

A universal, or domain independent ontology for spatial data is needed because space is a phenomenon that exists everywhere and is present in many kinds of human endeavour. Traditionally, universal phenomena like time and space have been modelled in different domains, according to domain specific requirements. Linked Data and the semantic web now offer a way to share data with many different perspectives, in a domain independent way. A domain independent ontology for time already exists: 0 . The time has now come for space to have a similar ontology. Practically, this will greatly increase interoperability of spatial data. Not only on the web: offline systems (e.g storage systems and libraries) could also benefit from having a single root model to depend on.

GeoSPARQL is a good candidate for evolving into a general ontology for spatial data because:
1. The Semantic Web allows direct open and modular access to all definitions.
2. OGC has a large canon for spatial data modelling ready for re-use. Existing OGC models have sound mathematical foundations that are applicable outside the geography domain.
3. OGC has been broadening its scope. Broadening the scope of GeoSPARQL should fit in nicely with that development. Examples of domains that are using different ways of working with spatial data, but increasingly do need to interoperate with geographic data are building information modelling (BIM) and 3D visualization.
4. OGC is an esteemed authority for standard specifications (although further collaboration with W3C would be beneficial). Widening the scope of GeoSPARQL would certainly mean the ontology becoming much bigger. Further modularization should prevent the ontology becoming unwieldy and users becoming overwhelmed with information which is not required for their purposes. Modularization can also be used to make distinctions between vector and coverage data, where required, but to share fundamentals too.

This subject has been discussed in the Spatial Data on the Web Working Group and is a project proposal in the Spatial Data on the Web Interest Group, found here: https://github.com/w3c/sdw/issues/1095

==== Extension 7: Availability in JSON-LD format

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=591

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/8

===== Category

Accessibility

===== Description

The GeoSPARQL ontology is available online in XML and TTL formats. JSON-LD could be added as an additional publication format, supported by content negotiation of course. This will allow easier consumption of the ontology by web pages. This, in turn, allows easier consultation of the ontology by humans. For example, parts of the ontology could be visualized as diagrams, or definitions of terms could be rendered as tooltips on web pages.

==== Extension 8: Extending GeoSPARQL by defining more vector literal types

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=585

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/6

===== Category

Geospatial encoding

===== Description

GeoSPARQL currently offers WKT and GML literal types which can be used to encode vector geometries. However, geospatial data formats are very heterogeneous and a variety of other data formats deserve to be encodable in GeoSPARQL in our opinion.

In the following we list the most likely candidates:
- GeoJSON: Very common throughout the Web
- GeoHash: Common has representations of vector data
- GPX: GPX Format used in GPS trackers
- KML Format by Google
- (H)(E)WKB/TWKB: Binary serializations of WKT often used as an internal storage format in databases

The following formats could be considered, but are in our opinion optional:
- LatLonText: Common format to display points in e.g. Wikidata or OSM
- GeoURI: Defacto standard for mobile phone geo urls
- Geobuf Format
- OSM Format: OSM XML
- Polyshape/EncodedPolyline: Format developed by Google to encode polylines/polyshapes
- SVG: Web standard for graphics in general
- X3D: Standard to visualize 3D geometries

Implementations of most of the described literals can be seen in an extension for rdf4j and an extension for Jena, and in a proposed ontology here: https://github.com/i3mainz/geosparql2.0

Possibly, other literal implementations are useful and could be discussed.

This PDF provides links to all the dataformat specifications and proposes how literal representations could look like: https://github.com/opengeospatial/geosemantics-dwg/blob/master/CR585attachment.pdf.

==== Extension 9: Extending the GeoSPARQL ontology with support for raster data

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/41

===== Category

Geospatial encoding

===== Description

GeoSPARQL is currently incapable of encoding and dealing with raster data.
However, raster data is essential for many geospatial applications and supported by many of relational geospatial databases such as POSTGIS.
Raster data even provides semantics, as interpretations of raster data can be given by interpreting the color codes of raster bands.
In order to integrate raster data into GeoSPARQL the following requirements need to be fulfilled:
- Extending the GeoSPARQL ontology to include support for GridCoverages
- Extending the GeoSPARQL ontology with raster literal types such as CovJSON,GMLCOV,GeoTIFF
- Extending the GeoSPARQL ontology with vocabularies to describe raster data content

==== Extension 10: Extending the GeoSPARQL ontology with raster data query capabilities

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/42

===== Category

Query language

===== Description

If the GeoSPARQL ontology is able to support raster data, new query capabilities are needed in order to use raster data in daily applications.
In particular the following query capabilities which are the norm in relational GIS databases should be adopted:
- Raster algebra operations
- Raster relation functions (ST_Within, ST_Covers...)
- Vectorization and Rasterization capabilities
- Raster modification capabilities (e.g. ST_AddBand)

==== Extension 11: Extending the GeoSPARQL ontology with full-featured 3D support

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/43

===== Category

Ontology

===== Description

GeoSPARQL currently only explicitly supports 2D geometries. 
However, work has already been done in defining ontologies for 3D geometries (e.g. https://github.com/w3c-geom-cg/geom or https://www.web3d.org/working-groups/x3d-semantic-web/charter). 
These ontologies should be checked and integrated into, or merged with, the GeoSPARQL ontology.

==== Extension 12: Extending the GeoSPARQL ontology with functions to handle 3D geometries

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/44

===== Category

Ontology

===== Description

The GeoSPARQL query language currently only supports functions capable of dealing with 2D geometries. However, with the emergence of standards such as CityGML which could be supported as GML literals, specific 3D-aware functions should be added to GeoSPARQL to accommodate such recent developments.
Suggestions:
- 3D-aware functions of the RCC8 calculus
- ST_Distance3D
- ST_Length3D
- ST_Difference3D

==== Extension 13: Extending the GeoSPARQL ontology with support for M and T coordinates

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/45

===== Category

Query language

===== Description

Many geospatial libraries such as JTS (https://github.com/locationtech/jts) provide explicit support for geometries with measurement (M) coordinates. These are useful in a variety of applications e.g. when a road is simplified in a query statement but users still would like to query the correct amount of kilometres since its start. The time coordinates (T) are useful when working with GNSS tracks in order to track per-point when a user went to a particular place. While the latter can also be achieved by modeling every point of a GNSS track as its own point geometry, it is unnecessary if the points provide no further semantic information apart from the time point. While the support XYZM or XYZMT coordinates is not a matter of GeoSPARQL itself but more of the formats which are supported as literals in the query language, GeoSPARQL could provide definitions of functions which are aware of these extended coordinate concepts such as:
- ST_M/ST_T
- ST_FilterByM/ST_FilterByT
- ST_PartOfGeometryBefore
- ST_PartOfGeometryAfter
- ST_PartOfGeometryAt

==== Extension 14: Propose how authoring metadata should be included

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/46

===== Category

Semantic improvement

===== Description

In AEC, authoring metadata (e.g. author, date, revision, etc.) is of high relevance for multiple aspects of collaboration, such as coordination and legal issues. Hence, the domains requires authoring metadata to be attached to any kind of information -- and with geometry oftentimes being the core structure for non-geometric information -- this is even more important for geometry descriptions. To avoid inconsistent and varying attachments of authoring metadata, we suggest to formulate a best practice for enhancing GeoSPARQL triples with authoring information, ideally by reusing existing concepts of provenance ontologies, e.g. PROV-O, DCTerms, etc.

==== Extension 15: Add concepts for accuracies and tolerances

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/47

===== Category

Semantic improvement / Increased Scope

===== Description

The AEC domain struggles with geometric representations of planned objects and built objects and corresponding tolerances and inaccuracies, respectively. Planned objects are created on a scratchpad, while construction sites do not offer perfect conditions to recreate the planned geometry completely. Depending on the construction material, the geometry descriptions are commonly enriched with tolerance values, ranging from millimeters (steelwork) to centimeters (masonry). For the geometry of already built objects, the (measured) accuracy is also not perfect, as measuring techniques cannot provide flawless representations. Furthermore, by processing or simplifying geometry descriptions (e.g. from point cloud to mesh), inaccuracies can occur, which are also of interest to attach (represented accuracy). Hence, the possibility to attach accuracies (measured or calculated accuracy) and tolerances would be beneficial for building geometry.  

==== Extension 16: Enable semantic descriptions of the applied geometry representation contexts

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/48

===== Category

Semantic improvement

===== Description

Some geometry schemes can contain a variety of geometry representation contexts (BREP, CSG, NURBS, etc.) but not all applications can deal with every geometry representation context. To ease the integration of geometry descriptions into applications, metadata regarding the geometry representation context at hand could help to automatically retrieve suitable descriptions only. Example: DWG can contain a 2D drawing, a 3D mesh and/or 3D BREP geometry.

==== Extension 17: Allow multiple modelling levels for connection patterns between objects and geometry descriptions

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/49

===== Category

Modelling patterns

===== Description

Currently, GeoSPARQL requires one intermediate node to attach geometry descriptions to objects. However, in some cases, this might be too complicated and reduce querying performance, while other cases might require additional nodes (e.g. version control). In the Ontology for Managing Geometry (OMG, https://w3id.org/omg), multiple levels for connecting geometry descriptions and objects exist. OMG level 1 implements direct connections between objects and their geometry description (omg:hasSimpleGeometryDescription and omg:hasComplexGeometryDescription), level 2 adds one intermediate node (omg:Geometry), similar to GeoSPARQL 1.0, and the third level adds another node (omg:GeometryState) for versioning purposes. The selection which level is used in a situation depends on the required features (balance between simplicity and functionality).

In AEC, for example, versioning, and thus level 3, is needed during (1) design phase of buildings and (2) for modeling change over time of a building (e.g. changes to building elements, geometry from multiple surveys over time), while data exchange without need for additional metadata would be most performant with level 1 and storage of certain planning stages would be ideally implemented with level 2 to allow multiple geometry descriptions. 

Also see the following publications:

- Wagner, A., Bonduel, M., Pauwels, P., & Uwe, R. (2019). Relating geometry descriptions to its derivatives on the web. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 304–313). Chania, Greece. https://doi.org/10.35490/EC3.2019.146 

- Bonduel, M., Wagner, A., Pauwels, P., Vergauwen, M., & Klein, R. (2019). Including widespread geometry formats in semantic graphs using RDF literals. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 341–350). Chania, Greece. https://doi.org/10.35490/EC3.2019.166 

==== Extension 18: Need for a universal linking method between objects and geometry descriptions in any existing schema

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/50

===== Category

Increased scope

===== Description

Geometry can be described in different ways than SFA/GML snippets in RDF literals. A uniform connector ontology with supplementary metadata would help collaboration across different domains and companies. Hence the different approaches to include geometry in a Semantic Web context should be allowed by the linking method: 1) RDF-based geometry following a dedicated ontology as the geometry schema (e.g. GEOM (https://github.com/w3c-geom-cg/geom), OntoBREP (https://github.com/OntoBREP/ontobrep), OCC (http://w3id.org/occ), etc.); 2) RDF literal embedding the content of a geometry file (~ GeoSPARQL 1.0 for 2D WKT and 2D GML); 3) RDF literal containing a reference to an external geometry file.

For each approach, a wide variety of geometry schemes exist for different use cases. All these schemes should be supported (i.e. binary or text-based, open or proprietary, 2D (vector or raster) or 3D (BREP, CSG, NURBS, point clouds, meshes), RDF-based or other (XML-based, JSON-based, SPFF-based, custom, etc.)). To achieve this support, we suggest the following adaptations:

- Binary geometry descriptions: GeoSPARQL 1.0 uses both the datatype property (e.g. geosparql:asWKT) and the datatype (e.g. geosparql:wktLiteral) to express the used geometry schema. Instead, the datatype could be used to add information about the used text encoding of the binary geometry descriptions (base64, hexadecimal, base32, base122, etc.) using XSD or custom datatypes

- RDF-based geometry descriptions: geosparql:hasSerialization cannot be used, as it is an owl:DatatypeProperty. We suggest to implement two properties for connecting geometry descriptions, as implemented in the Ontology for Managing Geometry (OMG, https://w3id.org/omg): omg:hasSimpleGeometryDescription a owl:DatatypeProperty -- to link to RDF literals;  omg:hasComplexGeometryDescription a owl:ObjectProperty -- to link to the first node of RDF-based geometry descriptions

- Links to external files:  Instead of making the file location an individual (node), we argue to add the URL/location as RDF literal with the datatype xsd:anyURI. Otherwise, if the location of the geometry file would change, the URI of the RDF node would have to be updated, which is against the COOL URIs best practice.

By widening the scope via the proposed adaptation, the serialisation of the geometry can no longer be defined in the datatype. Hence, a novel approach to identify the serialisation for automated processing by software applications is required. In OMG this issue is solved by creating a taxonomy, the File Ontology for Geometry formats (FOG, https://w3id.org/fog), that extends the OMG properties. Each FOG property corresponds with a geometry schema and is specialised further via subproperties to indicate the schema version and -- if the geometry schema demands/allows multiple files (e.g. a separate material, texture, … file) or serialisations -- the individual serialisation. 

- Remark: defining properties in FOG for every geometry schema, version, and serialisation that exist is impossible. The taxonomy can and should be extended by users (locally or by suggesting extensions to a centrally managed repository)
- Remark: if external files are integrated as proposed above, only one taxonomy has to be created for geometry schemes that are not RDF-based, in disregard of whether they are integrated as snippets (datatype properties) or external files (which would be object properties, if they would be represented by individuals instead of RDF literals)

Also see the following publications for OMG and FOG and their respective use cases:

- Wagner, A., Bonduel, M., Pauwels, P., & Uwe, R. (2019). Relating geometry descriptions to its derivatives on the web. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 304–313). Chania, Greece. https://doi.org/10.35490/EC3.2019.146 

- Bonduel, M., Wagner, A., Pauwels, P., Vergauwen, M., & Klein, R. (2019). Including widespread geometry formats in semantic graphs using RDF literals. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 341–350). Chania, Greece. https://doi.org/10.35490/EC3.2019.166 

NOTE: This extension proposal has some overlap with issues raised in extensions 8, 9 and 11

==== Extension 19: Terminology needed to express relations between geometry descriptions

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/51

===== Category

Semantic improvement / Increased scope

===== Description

If multiple geometry descriptions can be attached to one object, or if objects are related to each other, it would be useful to also define relations between the geometry descriptions directly, that are of other nature than purely topological. We propose to extend the schema to also describe the following relations: 

1. grouping of geometry descriptions, e.g. for use cases; 
2. describing derivations of multiple geometry descriptions, i.e. to ease maintaining consistent data; 
3. transforming geometry descriptions to avoid redundant geometry descriptions; 
4. referencing parts of a large geometry description as geometry representation of a smaller object

These relations are currently implemented in the Ontology for Managing Geometry (OMG, https://w3id.org/omg). The individual use cases and current implementations are presented below.

1. Grouping: In the AEC industry, geometry can be necessary in multiple use cases, e.g. heating calculation software needs BREP geometry of internal and external space volumes and their connections or an architect wants to communicate the geometry of a specific version of his design to a client. If the according geometry representations (BREP, mesh, CSG, etc.) of all relevant geometry descriptions could be extracted by a simple query that extracts the relevant group, these processes could be automated more swiftly. In OMG, this is currently implemented via a geometry context. Several omg:Geometry or omg:GeometryState (version) instances can be linked to an omg:GeometryContext instance via the omg:hasGeometryContext property.
2. Deriving: Derivation of geometry descriptions occur in two cases: either, a geometry is converted from one schema into another, or a geometry is processed for a certain use case. The first case is usually conducted due to software application interoperability, where one application outputs one schema and another application requires a different one. The second case has more diverse reasons, for example, a BREP/CSG/NURBS geometry could be modeled based on a point cloud or a mesh coming from a survey, a 3D BREP model is created from 2D CAD drawings (elevations, plans, sections), or certain parts of the geometry are filtered for simulations, e.g. only outside faces for raytracing simulations. This relation is currently implemented in OMG on both geometry description, as well as geometry version level via the omg:isDerivedFromGeometry and omg:isDerivedFromGeometryState properties, respectively. These properties can create links between two instances of omg:Geometry or omg:GeometryState to indicate the derivation or -- if version control is used -- potential derivations (e.g. a geometry in OBJ serialisation can be derived from geometries in STEP or DWG serialisations)
3. Transforming: A building model can contain a manyfold of identical objects, such as doors, that share the same geometrical form, but have a different location. The object’s geometry is supplied by the manufacturer, but the designer has to decide the location of each door in the building. If the geometry has to be copied for every instance of the object, this can immensely inflate the total size of geometry descriptions and also bears the danger of data inconsistency. For example, if the manufacturer changes a minor detail of the description, each copy needs to be adapted or replaced. Instead, the geometry instances could contain a transformation matrix and a link to the original geometry description, effectively reducing file size and risk for inconsistency. Currently, this relation is implemented in OMG on the omg:Geometry node level. The omg:transformsGeometry property can link between two instances of omg:Geometry, where the instantiated geometry (subject) has no individual geometry description (thus no omg:hasSimpleGeometryDescription / omg:hasComplexGeometryDescription), but only a transformation definition connected (matrix, vector, etc) while the origin geometry (object) contains the complete geometry description in its own custom coordinate system.
4. Referencing: During a modeling phase, it is easier to store the geometry in a single file using the native geometry schema of the modeling application. At the same time, it is relevant to know which parts of the larger geometry description correspond to an individual building object. Hence, subparts of the building model should be connected to individual building elements, if the applied geometry format allows this, e.g. by providing identifiers for parts of the geometry description. In OMG this relation is currently implemented via the omg:isPartOfGeometry property between two instances of omg:Geometry. The partial geometry (subject) is referenced using one or multiple omg:hasReferencedGeometryId properties (with subproperties per kind of identifier per geometry schema in File Ontology for Geometry formats (FOG, https://w3id.org/fog)) that can be applied to the main geometry (object) to extract the subgeometry by processing.

Also see the following publications for OMG and FOG:

- Wagner, A., Bonduel, M., Pauwels, P., & Uwe, R. (2019). Relating geometry descriptions to its derivatives on the web. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 304–313). Chania, Greece. https://doi.org/10.35490/EC3.2019.146 

- Bonduel, M., Wagner, A., Pauwels, P., Vergauwen, M., & Klein, R. (2019). Including widespread geometry formats in semantic graphs using RDF literals. In Proceedings of the European Conference on Computing in Construction (EC3 2019) (pp. 341–350). Chania, Greece. https://doi.org/10.35490/EC3.2019.166 

==== Extension 20: Support for parametric geometry descriptions via links between a non-geometric property and geometric properties

===== Standards Tracker Change Request URI

This issue has not yet been added to the OGC issuue tracker (http://ogc.standardstracker.org/).

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/52

===== Category

Semantic improvement / Increased scope

===== Description

During the design phase of a building, a series of geometric descriptions are made based on input parameters (lengths, size, location, orientation). These parameters are commonly also part of the non-geometric description, causing redundant information. In traditional descriptions, such as the Industry Foundation Classes (IFC), this can lead to the non-geometric description contradicting the geometric one, since they are not updated accordingly. For example, a wall can be defined in IFC, where the height of the wall is a non-geometric property, while the extrusion of the geometry is stored separately. The non-geometric property is neither connected to the extrusion nor automatically updated, when the geometry changes, resulting in the potential of inconsistent data. Thus, a link between related properties from geometric and non-geometric descriptions should be established, to ease the detection of contradicting data and the subsequent updating process.

In the Ontology for Managing Geometry (OMG, https://w3id.org/omg), a first implementation of such links is realised. For one, the omg:isExplicitlyDerivedFrom property can be applied in cases, a geometric property of RDF-based geometry (object) and a non-geometric (subject) property describe exactly the same situation (e.g. the height/extrusion), where a chain axiom can be used to automatically update the according values. On the other hand, the omg:isImplicitlyDerivedFrom property can be applied to indicate that a non-geometric property (subject) can be derived from a geometry description (object), as is the case for volumes or surface areas.

- Remark: adding metadata regarding the used coordinate system, units and other metadata as mentioned in extension 1 and 4 can also result in double information.  Some geometry schemas such as OBJ are unitless so additional info on the length unit is useful, while others allow to define the used units internally (e.g. STEP) or have a fixed length unit defined in the schema (e.g. glTF uses metre). Adding metadata in RDF for OBJ geometry description enriches the knowledge over the geometry. If this is also added for STEP or glTF geometry, this results in redundant data, but the metadata is now externalized in RDF can thus be queried directly (no interpretation needed).

=== Defects reported in GeoSPARQL 1.0

==== Bug 1: Corrections of example data and queries

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=173

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/4

===== Category

Documentation bug

===== Description

Errors in example data and queries might lead to wrong implementations. In the given example data in B.1. (page 51) the LineString start with (( and ends with )), although it must be single brackets.

In the third example query in B.2 (page 52) the subject of the fifth triple pattern is a variable called ?my:D although is should be no variable (my:D).

In the fourth example query in B.2 (page 54) the URL given in the prefix definition for geof is wrong. Instead of < 0 > it must be < 1 >

==== Bug 2: GeoSPARQL Schema v1.0.1: hasDefaultGeometry

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=548

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/5

===== Category

Documentation bug

===== Description

There is a mismatch between the published GeoSPARQL standard v1.0 (11-052r4) and the schema v1.0.1 ( 0 ).

On 8.3.12, page 13, of the standard is defined the property hasDefaultGeometry.
The schema defines the property instead as defaultGeometry but with an otherwise equivalent definition. The schema does not contain a hadDefaultGeometry property.

This mismatch prevents RDFS and OWL inferencing being performed correctly on a dataset written to comply with the standard.

Please can the schema be updated and new version issued.

==== Change 1: Decouple CRS and WKT

===== Standards Tracker Change Request URI

http://ogc.standardstracker.org/show_request.cgi?id=595

===== GitHub Issue URI

https://github.com/opengeospatial/geosemantics-dwg/issues/10

===== Category

Coordinate Reference System support

===== Description

WKT seems a good way to easily encode geographic geometry, but the datatype geo:wktLiteral makes it hard to work with GeoSPARQL. In a next version, there should be an option to use only a WKT literal and use a different way to express the CRS of a geometry. Reasons why concatenation of CRS URI and WKT can be considered bad design are:

. GeoSPARQL deviates from the WKT standard, resulting in poor software support.
. Allowing not to specify a CRS and defaulting to CRS84 may be useful in North America, but is of little value for serious usage in other parts of the world.
. The proper data type for expression of CRS is an IRI. Therefore it should be defined as such, not as part of a string literal.
. Especially when non-geographical geometry is considered, CRS is not necessarily a known property. Therefore it should be possible to leave out CRS data in publications, without this resulting in wrong interpretations.
. CRS can be considered an intrinsic or fundamental aspect of geometry, but so are other properties like dimensionality or accuracy. This does not mean all of this information should be lumped together in one literal.

It seems better to introduce a new property for CRS and to let WKT literals be just WKT literals. Should a new property for indicating CRS be introduced, it would be good to allow it to be applied not only to individual geometries, but to geometry collections too.
