== Other informative information about the work of this SWG

=== Collaboration

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////
It is proposed that the work of this SWG be conducted openly on GitHub, as the work of the motivating GeoSemantics DWG is.


=== Similar or Applicable Standards Work (OGC and Elsewhere)

////
The following standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

OASIS BPEL
IETF HTTP

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.
////
This proposed SWG is to enhance an existing OGC standard - an ontology - however the Best Practices for ontology publication have changed since the original GeoSPARQL publication. The ontology publication methods of other standards bodies, particulary the W3C who continuously generates new stnadard ontologies, will be considered to determine appropriate, Best Practice, ontology publication. 

This may include the use of tools to automatically generate human-readable ontology versions from the technical ontology artifact, such as those used by inputs to this work, for example the http://linked.data.gov.au/def/geox[GeoSPARQL Extensions Ontology].  

It may also include the description of a GeosPARQL v2 as a *profile* (of GeoSPARQL v1 and perhaps other ontologies) as well as an ontology, in line with recent work by OGC members and others to establish standard ways of indicating the dependencies between stadards, as per https://www.w3.org/TR/dx-prof/[The Profiles Vocabulary].


=== Details of first meeting

////
Example:
The first meeting of the SWG will be held by telephone conference call at 10AM EDT on 1 October 2007. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.
////

=== Projected on-going meeting schedule

////
Example:
The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.
////

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|J. Abhayaratna | PSMA Australia
|L.E. van den Brink | Geonovum
|Nicholas J. Car | SURROUND Australia Pty Ltd
|===

=== Conveners

////
Name of individual(s) who started the SWG process. Could be the lead for an RFC submission, an OGC staff person, or an individual who believes it is time for a revision to an adopted standard.
////

|===
|Name |Organization
|J. Abhayaratna | PSMA Australia
|L.E. van den Brink | Geonovum
|===

