== Other informative information about the work of this SWG

=== Collaboration

==== bSI

GIS/BIM integration has been a long-standing challenge. bSI has a strong community using controlled vocabularies, so identifying how these may be used in the context of OGC standards such as OGC API Features, CityGML, IndoorGML, MUDDI etc is a problem of standardising terminology referencing mechanisms.

"On behalf of buildingSMART International (bSI), I am writing to express our strong interest in the OGC Call for Participation for the Vocabulary Service Standard (https://www.ogc.org/requests/vocabulary-service-standard/). We see significant synergy between this initiative and our buildingSMART Data Dictionary (bSDD) service (read more: https://www.buildingsmart.org/users/services/buildingsmart-data-dictionary/).

In short, the bSDD is a service for sharing and accessing data dictionaries to be used in BIM data, information requirements etc. The service is to a great extent based on the ISO23386 and ISO12006-3 on interconnected data dictionaries. As of today, there are 195 organisations who published over 300 data dictionaries in the bSDD, all can be browsed here: https://search.bsdd.buildingsmart.org/. The service has around 1000 unique daily users doing around 3M requests a month. We also provide an open API (JSON, RDF) to enable easy integrations with software, and there are 26 known software integrations with the bSDD.

As you know, the OGC and bSI have a longstanding Memorandum of Understanding, renewed in 2023, fostering cooperation in standards development and interoperability between BIM and GIS (more on MOU: https://www.buildingsmart.org/buildingsmart-international-and-geospatial-world-sign-mou-to-advance-bim-and-gis-workflows/). The Vocabulary Service Standard goals reflect the purpose and to great extent capabilities that the bSDD provides. Many of the ideas you describe are already implemented and actively used in the bSDD. By aligning and potentially integrating these efforts, I believe we can harmonize access and enhance great interoperability and improved consistency of BIM and GIS data.
"

=== Similar or Applicable Standards Work (OGC and Elsewhere)

// Review and update normative references

==== W3C/OGC Spatial Data on the Web Working Group

===== Scope of Activity

This group operates within the W3C as well as the OGC in order to develop and maintain vocabularies and best practices that encourage better sharing of spatial data on the Web; and identify areas where Standards should be developed jointly by both W3C and the Open Geospatial Consortium (OGC). It allows members of both organizations to collaborate in the creation of standards an best practices related to both Web and spatial data.

===== Web Site(s)

- https://www.w3.org/2017/sdwwg/

===== Source Repositories

- https://github.com/w3c/sdw

===== Liaisons

- Luis de Sousa (co-chair)
- Rob Atkinson (co-chair)

=== Other Related Work

=== Details of first meeting

TBD

=== Projected on-going meeting schedule

The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC Member Meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter Members. The Charter Members agree to the SoW and IPR terms as defined in this charter. The Charter Members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page.

|===
|N.J. Car | KurrawongAI
|===

=== Conveners
TBD
|===
|Name |Organization

|===
