name: build adocs

on: [workflow_dispatch] 
  
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor dcat swg charter
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor geodcat_swg_charter/swg_charter.adoc"
    - name: Get build container
      id: adocpdfbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor-pdf geodcat_swg_charter/swg_charter.adoc"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: commit generated docs
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version
      with:
          add: .
          message: "Generated charter doc"
          default_author: github_actions
    
