== Business Value Proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////
DCAT is a widely used metadata standard for datasets and data access services, tpyically within a spatio-temporal context. Some basic temporal and geographic properties have been adopted within the DCAT v2 <<DCAT>> and planned v3 <<DCAT3>>, however these do not address the full range of requirements identified in the <<GeoDCAT-AP>> Discussion paper. 

=== Value to the OGC
To maintain its place as the provider of standards for description and access to spatio-temporal data the OGC should provide guidance on representation of spatio-temporal concepts in data catalogues. <<GeoDCAT-AP>> is already referenced in the Spatial Data on the Web Best Practice <<SDWBP>>. The SWG will support publishing this as a normative resource, supporting the rationale for following SDWBP in general.
In addition, the management of a family od sub-profiles of GeoDCAT may be defined to standardise the description of OGC API usage in such catalogues. 

=== Value to the OGC Membership
Normative publication of GeoDCAT and API-centric implementation profiles provides a simplified pathway to assimilation of OGC standards into deployed systems.
In addition, formalised publication and identification supports the publicatioon and access via FAIR principles of supporting human and mcahine-readable resources to facilitate and validate implementations.

=== Value to the geospatial community
The larger geospatial community will benefit from the standardisation of description of geospatial data and access services in DCAT based datacatalogs.

=== Value to the wider IT community
The publication of a formal profile of DCAT will present a best practice for the domain specialisation of general data model standards, and a pattern for further specialisation as required.
