== Other informative information about the work of this SWG

=== Collaboration

The GeoDCAT SWG will use

- Project Related Documentation;

- Creation and management of outstanding work items, using Standards Tracker as the authoritative register;

- Prioritisation of work items into iterations of work; and

- The Standard Document itself.

It is proposed that the work of this SWG be conducted openly on GitHub, as the work of the motivating GeoSemantics DWG is.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

// Review and update normative references

==== DCAT-AP


==== W3C Linked Building Data Community Group

===== Scope of Activity

The European Union publishes <<DCAT-AP>> — a profile of DCAT to meet administrative requirements for data publication in EU context.

This application profile is a specification for metadata records to meet the specific application needs of data portals in Europe while providing semantic interoperability with other applications on the basis of reuse of established controlled vocabularies (e.g., EuroVoc) and mappings to existing metadata vocabularies (e.g., Dublin Core, SDMX, INSPIRE metadata).

GeoDCAT is expected to be combined with DCAT-AP to realise a normative implementation of <<GeoDCAT-AP>>

===== Web Site(s)

- https://joinup.ec.europa.eu/solution/dcat-application-profile-data-portals-europe

===== Source Repositories

- https://github.com/SEMICeu/DCAT-AP

===== Liaisons

- Andrea Perego
- Antoine Isaac

=

==== W3C/OGC Spatial Data on the Web Working Group

===== Scope of Activity

This group operates within the W3C as well as the OGC in order to develop and maintain vocabularies and best practices that encourage better sharing of spatial data on the Web; and identify areas where standards should be developed jointly by both W3C and the Open Geospatial Consortium (OGC). It allows members of both organizations to collaborate in the creation of standards an best practices related to both Web and spatial data.



===== Web Site(s)

- https://www.w3.org/2017/sdwwg/

===== Source Repositories

- https://github.com/w3c/sdw

===== Liaisons

- Linda van den Brink

- Jeremy Tandy

=== Other Related Work


=== Details of first meeting

The first meeting of the SWG will be held by telephone conference call at 6AM EDT on the first Thursday immediately following the week of Technical Committee approval of this Charter. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.

=== Projected on-going meeting schedule

The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter Members. The Charter Members agree to the SoW and IPR terms as defined in this charter. The Charter Members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page.

|===
|L.E. van den Brink | Geonovum
|N.J. Car | SURROUND Australia Pty Ltd
|J. Maso Pau | CREAF
|L. Alemany Gómez | Centro Nacional de Información Geográfica
|B. de Lathouwer | Gemeente Rotterdam
|R. Atkinson | OGC Innovation Program
|J. Escriu | European Commission Joint Research Centre
|===

=== Conveners

|===
|Name |Organization
|L.E. van den Brink | Geonovum
|J. Maso Pau | CREAF
|===
